---

my_var: "this is set via the local env"
local_var: "this is set via the local env"

development_environments:
    - python
  #- mysql
  #- npm
  #- php
  #- sqlite

docker_installed: "{{ True if ansible_memtotal_mb >= 4000 else False }}"

term_xrandr_primary_resolution: '1600x900'
term_xrandr_custom_mode: True

term_install_vim_ycm: "{{ False if ansible_distribution == 'Debian' else True }}"

# TODO set these as facts
ethernet_interface: "{{ ansible_interfaces|default([]) | select('match', '^e') | list | join('') }}"
wireless_interface: "{{ ansible_interfaces|default([]) | select('match', '^w') | list | join('') }}"
