---

my_var: "this is set via the local env"
local_var: "this is set via the local env"

development_environments:
  - docker
  #- mysql
  #- npm
  #- php
  #- ruby
  #- sqlite

hipchat_installed: False

term_xrandr_primary_resolution: '1600x900'
term_xrandr_custom_mode: True
