#!/usr/bin/env python3

from argparse import ArgumentParser
from argparse import RawTextHelpFormatter
import os
import shlex
import subprocess
import sys


class AnsiblePlaybook():

    def __init__(self):
        ''' initialize the object '''

        self.pip_requirements = ['ansible', 'Jinja2']
        self.system_deps_packages = [
            'git',
            'python',
            'python-apt',
            'python-dev',
            'python-virtualenv',
            'python3',
        ]

        self.venv_dir = os.path.join(os.environ['HOME'], '.virtualenvs/sz-Ansible-playbook')

        os.environ = AnsiblePlaybook.get_clean_env()

        self.ArgumentParser = ArgumentParser(description='Ansible-playbook - ' +
                                                         'wrapper for running Ansible playbooks',
                                             formatter_class=RawTextHelpFormatter)

        self.wrapper_args, self.playbook_args = self.parse_arguments()
        self.handle_arguments()

    def run(self):
        ''' run the playbook '''

        self.virtualenv_workon()
        sys.exit(subprocess.call(['ansible-playbook'] + self.playbook_args,
                                 env=os.environ,
                                 cwd=os.path.abspath(os.path.dirname(__file__))))

    def bootstrap(self):
        self._system_deps()
        sys.exit(0)

    def _virtualenv_make(self, venv_dir):
        ''' make a virtualenv in the specified directory '''

        error = 0

        if venv_dir:
            os.makedirs(venv_dir, mode=0o755, exist_ok=True)
            error = os.system("virtualenv {}".format(venv_dir))
        else:
            error = 1

        if error:
            sys.exit("could not create venv_dir {}".format(venv_dir))

    def _virtualenv_activate(self, venv_dir, install=True):
        ''' activate a virtualenv, creating one if specified '''

        activate_path = os.path.join(venv_dir, "bin/activate_this.py")
        with open(activate_path) as f:
            code = compile(f.read(), activate_path, 'exec')
            exec(code, dict(__file__=activate_path))

        if install:
            subprocess.call(shlex.split('pip install --upgrade {}'.format(' '.join(self.pip_requirements))))

    def _system_deps(self):
        ''' install system dependencies '''

        if os.system('sudo apt-get update && sudo apt-get install -y {}'.format(' '.join(self.system_deps_packages))):
            sys.exit("failed to install system dependencies")

    def parse_arguments(self):
        ''' parse command line arguments '''

        environment_inventory = self.ArgumentParser.add_mutually_exclusive_group(required=True)

        environment_inventory \
            .add_argument('-i', '--inventory-file',
                          dest='inventory_file',
                          help='static inventory file',
                          type=str)

        environment_inventory \
            .add_argument('--bootstrap',
                          dest='bootstrap',
                          action='store_true',
                          help='bootstrap your Ansible environment')

        arg_list = {"--debug": {
                        "action": 'store_true',
                        "help": 'Enable debug mode',
                    },
                    "--venv": {
                        "dest": 'venv',
                        "help": 'Virtual environment directory. (Default: {})'.format(self.venv_dir),
                        "default": self.venv_dir,
                    }, }
        for arg_name, arg_opts in arg_list.items():
            self.ArgumentParser.add_argument(arg_name, **arg_opts)

        return self.ArgumentParser.parse_known_args()

    def handle_arguments(self):
        ''' handle the command line arguments '''

        os.environ['_ANSIBLE_INVENTORY_DEBUG'] = str(self.wrapper_args.debug)

        if self.wrapper_args.inventory_file:
            self.playbook_args.append('--inventory-file')
            self.playbook_args.append(self.wrapper_args.inventory_file)

        if self.wrapper_args.bootstrap:
            self.bootstrap()

        if self.wrapper_args.venv:
            self.venv_dir = os.path.expanduser(self.wrapper_args.venv)

    def virtualenv_workon(self):
        ''' create and load a python virtualenv into current env '''

        if not os.path.exists(self.venv_dir):
            self._virtualenv_make(self.venv_dir)
        self._virtualenv_activate(self.venv_dir)

    @staticmethod
    def get_clean_env():
        ''' return a clean environment '''

        return {
            'USER': os.environ['USER'],
            'HOME': os.environ['HOME'],
            'PATH': os.environ['PATH'],
            'PS1': '$',
            'TERM': os.environ.get('TERM', ''),
            'SSH_AGENT_PID': os.environ.get('SSH_AGENT_PID', ''),
            'SSH_AUTH_SOCK': os.environ.get('SSH_AUTH_SOCK', ''),
        }

if __name__ == '__main__':
    ansible_playbook = AnsiblePlaybook()
    ansible_playbook.run()
