---

- import_playbook: facts.yml

- name: prepare a desktop
  hosts: localhosts
  roles:
      - { role: apt_get_upgrade, tags: apt_get_upgrade }
      - { role: term, tags: term }
      - { role: sshd, tags: sshd,
          when: sshd_installed|default(true)|bool == true
        }
      - { role: boot, tags: boot }
      - { role: sudo, tags: sudo }
      - { role: ssh_client, tags: ssh_client }
      - { role: git, tags: git }
      - { role: development, tags: development }
      # Window management
      - { role: xorg, tags: xorg }
      - { role: i3, tags: i3 }
      - { role: roles-next/desktop, tags: desktop }
      - { role: roles-installed/angstwad.docker_ubuntu,
          tags: docker,
          become: true }
      - { role: roles-installed/oefenweb.virtualbox,
          tags: virtualbox,
          when: virtualbox_installed|default(False)|bool,
          become: true }
