---

- include: facts.yml

- name: prepare a desktop
  hosts: localhost
  roles:
    - { role: apt_get_upgrade, tags: apt_get_upgrade }
    - { role: grub, tags: grub }
    - { role: sudo, tags: sudo }
