---

- include: facts.yml

- name: prepare a desktop
  hosts: localhost
  roles:
      - { role: secrets, tags: [always,secrets] }
      - { role: apt_get_upgrade, tags: apt_get_upgrade }
      - { role: term, tags: term }
      - { role: sshd, tags: sshd,
            sshd_config_opts_enabled: [ 'hardened_crypto' ]
        }
      - { role: grub, tags: grub }
      - { role: sudo, tags: sudo }
      - { role: ssh_client, tags: ssh_client }
      - { role: development, tags: development,
            development_environments: [php, mysql]
        }
      # Window management
      - { role: xorg, tags: xorg }
      - { role: i3, tags: i3 }
