---
- name: gather host facts
  hosts: all
  gather_facts: true
  tasks:
    - debug:
        var: inventory_hostname
      tags: always
    - debug:
        var: ansible_python_interpreter
      tags: always
    - debug:
        var: ansible_form_factor
      tags: always
    - debug:
        var: hostvars[inventory_hostname]
      tags: always
    - debug:
        msg: "Wireless Device: {{ ansible_interfaces|default([]) | select('match', '^w') | list | join('')}}"
      tags: always
