---

- name: install packages
  become: true
  apt: >
      name={{ item }}
      state=latest
      update_cache=true
      cache_valid_time=3600
  register: term_install_packages_result
  with_items: "{{ term_packages }}"
  tags: packages

- name: install packages result
  debug: var=term_install_packages_result

- name: uninstall packages
  become: true
  apt: >
      name={{ item }}
      state=absent
      update_cache=true
      cache_valid_time=3600
  register: term_uninstall_packages_result
  with_items: "{{ term_uninstall_packages }}"
  tags: packages

- name: uninstall packages result
  debug: var=term_uninstall_packages_result

- name: mk urxvt-perls dir
  file: >
      path={{ term_perls_path }}
      state=directory
      mode=750
  when: term_perls_path != ""

- name: clone urxvt-perls repo from github
  git: >
      repo={{ git_base_repo }}/urxvt-perls
      dest={{ term_perls_path }}
      accept_hostkey=yes
  when:
      - term_perls_path != ""
      - git_base_repo|default('') != ""
  tags: packages

- name: mk Vundle dir
  file: >
      path={{ term_vundle_path }}
      state=directory
      mode=750
  when: term_vundle_path != ""
  tags:
      - vim

- name: clone Vundle repo from github
  git: >
      repo=https://github.com/gmarik/Vundle.vim.git
      dest={{ term_vundle_path }}/Vundle.vim
      accept_hostkey=yes
  when:
      - term_vundle_path != ""
  tags:
      - packages
      - vim

- name: install templates
  template: >
      src={{ item.name|default(item) }}.j2
      dest={{ ansible_env.HOME }}/{{ item.name|default(item) }}
      mode={{ item.mode|default(640) }}
  with_items: "{{ term_templates }}"
  tags:
      - vim

- name: install files
  copy: >
      src={{ item }}
      dest={{ ansible_env.HOME }}/{{ item }}
      mode=640
  with_items: "{{ term_files }}"
  tags:
      - vim

- name: mk bin dir
  file: >
      path={{ term_bin_path }}
      state=directory
      mode=750

- name: install bin
  copy: >
      src={{ item }}
      dest={{ ansible_env.HOME }}/{{ item }}
      mode=750
  with_items: "{{ term_bin }}"

- name: install vundle packages
  shell: >
      echo "\n" | vim -c "VundleUpdate" -c "q" -c "q"
  register: vundle_package_install
  tags:
      - packages
      - vim

- name: show output of install Vundle packages
  debug: var=vundle_package_install
  tags:
      - packages
      - vim

- name: compile YouCompleteMe
  shell: ./install.py --clang-completer
  args:
    chdir: "{{ term_vundle_path }}/YouCompleteMe"
    creates: "{{ term_vundle_path }}/YouCompleteMe/third_party/ycmd/ycm_core.so"
  register: compile_YouCompleteMe
  tags:
      - packages
      - vim

- name: show output of compiling YouCompleteMe
  debug: var=compile_YouCompleteMe
  tags:
      - packages
      - vim
