---

- name: add default grub config
  become: true
  template:
    src: 'default/grub.j2'
    dest: '/etc/default/grub'
    mode: 644
    owner: root
    group: root
  notify:
    - grub update
  tags:
    - templates

- name: add failsafe config
  become: true
  template:
    src: 'init/failsafe.conf.j2'
    dest: '/etc/init/failsafe.conf'
    mode: 644
    owner: root
    group: root
  tags:
    - templates
