---

- name: install packages
  become: true
  apt: >
      name={{ item }}
      state=latest
      update_cache=true
  with_items:
    - "{{ xorg_packages }}"
  register: xorg_packages_output
  tags: packages

- debug: var=xorg_packages_output

- name: install templates
  template: >
      src={{ item }}.j2
      dest={{ ansible_env.HOME }}/{{ item }}
      mode=640
  with_items:
    - "{{ xorg_templates }}"

- name: install files
  copy: >
      src={{ item }}
      dest={{ ansible_env.HOME }}/{{ item }}
      mode=640
  with_items:
    - "{{ xorg_files }}"
