term_perls_path: "{{ ansible_env.HOME }}/.urxvt/ext"
term_bin_path: "{{ ansible_env.HOME }}/bin"
term_vundle_path: "{{ ansible_env.HOME }}/.vim/bundle"

term_packages:
    - build-essential
    - cmake
    - curl
    - fortune
    - glances
    - htop
    - httpie
    - iftop
    - make
    - ncdu
    - ngrep
    - pv
    - rxvt-unicode-256color
    - sshpass
    - strace
    - sysstat
    - tree
    - ttf-ancient-fonts
    - unzip
    #- wicd-curses
    - xclip

term_uninstall_packages:
    - vim-tiny

term_templates:
    - .Xmodmap
    - .Xresources
    - .xinitrc
    - .vimrc
    - { name: 'bin/xrandr_laptop.sh', mode: '0750' }
    - { name: 'bin/backup_to_usb', mode: '0750' }

term_files:
    - .bash_aliases
    - .bash_logout
    - .bashrc
    - .git-prompt.sh

term_bin:
    - bin/Ansible-playbook
    - bin/headphones
    - bin/incognito
    - bin/randomize_mac.py
    - bin/xterm_colors.sh
    - bin/xterm_colors_pacman.sh

term_xrandr_primary_resolution: '800x600'
term_xrandr_custom_mode: False
