---

development_packages: []

development_environment_packages:
    docker:
        - docker-engine
    mysql:
        - mysql-client-5.6
        - mysql-client-core-5.6
        - mysql-common
    npm:
        - npm
    php:
        - php5
        - php5-json
        - php5-mcrypt
        - php5-mysql
        - php5-pgsql
        - php5-sqlite
    postgresql:
        - postgresql-client-9.3
    python:
        - python3.4
        - python-virtualenv
    ruby:
        - ruby2.2
        - ruby2.2-dev
    sqlite:
        - sqlite3
