---
- name: add i3wm ubuntu repo
  become: true
  apt_repository:
    repo: 'deb http://debian.sur5r.net/i3/ trusty universe'
    state: present
  when:
      - ansible_distribution == 'Ubuntu'
      - ansible_distribution_major_version|int < 17
  register: i3_packages_output
  tags: packages

- name: install i3 unauthenticated packages on ubuntu
  become: true
  apt:
    name: "{{ i3_packages_unauthenticated }}"
    state: latest
    update_cache: true
    allow_unauthenticated: yes
  when:
      - ansible_distribution == 'Ubuntu'
      - ansible_distribution_major_version|int < 17
  register: i3_packages_output
  tags: packages

- name: install i3wm
  become: true
  apt:
    name: "{{ i3_packages }}"
    state: latest
    update_cache: true
  register: i3_packages_output
  tags: packages

- debug:
    var: i3_packages_output

- name: create a directory for screenshots
  file:
    path: "{{ ansible_env.HOME }}/{{ i3_screenshot_directory }}"
    state: directory
    mode: 0770

- name: create .i3 dir
  file:
    path: "{{ ansible_env.HOME }}/.i3"
    state: directory
    mode: 0770

- name: install i3 templates
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ ansible_env.HOME }}/{{ item.src }}"
    mode: "{{ item.get('mode', 0664) }}"
  with_items:
    - "{{ i3_templates }}"
