---

- include: do_install.yml
  when: i3_do_install |default(False) |bool == True or global_do_install |default(False) |bool == True

- include: do_remove.yml
  when: i3_do_remove |default(False) |bool == True
