---

- name: install packages
  become: true
  apt: >
      name={{ item }}
      state=present
      update_cache=true
  with_items: "{{ git_packages }}"
  register: git_install_packages
  tags: packages

- name: display output of installing packages
  debug:
    var: git_install_packages

- name: create configuration directory
  file:
      path: "{{ ansible_env.HOME }}/.config/git"
      state: directory
      mode: 0775

- name: install templates
  template: >
      src={{ item }}.j2
      dest={{ ansible_env.HOME }}/.config/git/{{ item }}
      mode=640
  with_items: "{{ git_templates }}"

- name: install files
  copy: >
      src={{ item }}
      dest={{ ansible_env.HOME }}/{{ item }}
      mode=640
  with_items: "{{ git_files }}"
