---

- name: reboot_machine
  become: true
  command: shutdown -r now "Ansible triggered reboot, don't panic."
  async: 0
  poll: 0
  ignore_errors: true

- name: reboot_machine_wait
  become: false
  local_action: wait_for host={{ inventory_hostname }} state=started
