---

- name: add dockerproject GPG key
  become: true
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  when:
    - ansible_distribution == 'Ubuntu'
    - "{{ 'docker' in development_environments }}"
  tags: packages

- name: add dockerproject repo
  become: true
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main
  when:
    - ansible_distribution == 'Ubuntu'
    - "{{ 'docker' in development_environments }}"
  tags: packages

- name: add brightbox ppa
  become: true
  apt_repository: >
    repo=ppa:brightbox/ruby-ng
  when:
    - ansible_distribution == 'Ubuntu'
    - "{{ 'ruby' in development_environments }}"
  tags: packages

- name: install development packages on ubuntu
  become: true
  apt: >
    name={{ item }}
    state=latest
    update_cache=true
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - "{{ development_packages }}"
  register: development_packages_output
  tags: packages

- name: show installation output
  debug: var=development_packages_output

- name: install development environment packages
  become: true
  apt: >
    name={{ item.value }}
    state=latest
    update_cache=true
  when:
    - ansible_distribution == 'Ubuntu'
    - item.key in development_environments
  with_dict: "{{ development_environment_packages }}"
  register: development_environment_packages_output
  tags: packages

- name: show installation output
  debug: var=development_environment_packages_output

- name: include php development tasks
  include: do_install_php.yml
  when: "'php' in development_environments"

- name: include ruby development tasks
  include: do_install_ruby.yml
  when: "'ruby' in development_environments"
