---

- name: install development packages on ubuntu
  become: true
  apt: >
    name={{ item }}
    state=latest
    update_cache=true
  when: ansible_distribution == 'Ubuntu'
  with_items: development_packages
  register: development_packages_output
  tags: packages

- name: show installation output
  debug: var=development_packages_output

- name: install development environment packages
  become: true
  apt: >
    name={{ item.value }}
    state=latest
    update_cache=true
  when:
    - ansible_distribution == 'Ubuntu'
    - item.key in development_environments
  with_dict: "{{ development_environment_packages }}"
  register: development_environment_packages_output
  tags: packages

- name: show installation output
  debug: var=development_environment_packages_output

- name: include php development tasks
  include: do_install_php.yml
  when: "'php' in development_environments"
