---

- name: install bin
  copy: >
      src={{ item }}
      dest={{ ansible_env.HOME }}/{{ item }}
      mode=0750
  with_items:
    - "{{ development_php_bin }}"

- name: enable php modules
  become: true
  command: php5enmod {{ item }}
  with_items:
    - "{{ development_php_mods }}"
