---

- name: remove development packages on ubuntu
  become: true
  apt:
    name: "{{ development_packages }}"
    state: absent
    update_cache: true
  when: ansible_distribution == 'Ubuntu'
  tags: packages
