ssh_client_dot_path: "{{ ansible_env.HOME }}/.ssh/"

ssh_client_packages:
    - openssh-client
    - sshfs

ssh_client_templates:
#    - { name: config, mode: 0750 }
    - { name: id_rsa, mode: '0600' }
    - { name: id_rsa.pub, mode: '0640' }
    - { name: id_ed25519, mode: '0600' }
    - { name: id_ed25519.pub, mode: '0640' }
    - { name: authorized_keys, mode: '0750' }
