---

- name: install packages
  become: true
  apt: >
      name={{ ssh_client_packages }}
      state=present
      update_cache=true
      cache_valid_time=3600
  register: ssh_client_packages_output
  tags: packages

- debug: var=ssh_client_packages_output

- name: create ssh directory
  file:
      path: "{{ ssh_client_dot_path }}"
      state: directory
      mode: 0700

- name: install templates
  template: >
      src={{ item.name }}.j2
      dest={{ ssh_client_dot_path }}/{{ item.name }}
      mode={{ item.mode }}
  with_items:
    - "{{ ssh_client_templates }}"
