---

- name: install packages
  become: true
  apt: >
      name={{ item }}
      state=present
      update_cache=true
      cache_valid_time=3600
  tags: packages
  register: ssh_client_packages_output
  with_items: ssh_client_packages

- debug: var=ssh_client_packages_output

- name: install templates
  template: >
      src={{ item.name }}.j2
      dest={{ ssh_client_dot_path }}/{{ item.name }}
      mode={{ item.mode }}
  with_items: ssh_client_templates

- name: add {{ ansible_env.USER }} to fuse
  become: true
  user: >
    name={{ ansible_env.USER }}
    append=true
    groups=fuse
