---

development_environments:
    - python

sshd_installed: False
term_xrandr_primary_resolution: '1920x1080'
virtualbox_installed: False

wireless_interface: 'wlp1s0'
ethernet_interface: 'enp0s31f6'
