---

- name: add default grub config
  template:
    src: 'default_grub.j2'
    dest: '/etc/default/grub'
    mode: 644
    owner: root
    group: root
  notify:
    - grub update
  tags:
    - templates
