---

- name: install desktop packages (apt)
  become: True
  apt:
      name: "{{ desktop_packages }}"
      state: latest

- name: install desktop packages (snap)
  become: True
  snap:
      name: "{{ desktop_snap_packages }}"
      state: present
